CREATE TABLE IF NOT EXISTS events (
  event_id INTEGER NOT NULL,
  event_date INTEGER NOT NULL,
  source_name TEXT,
  source_sectors TEXT,
  source_country TEXT,
  event_text TEXT,
  cameo_code TEXT,
  intensity REAL,
  target_name TEXT,
  target_sectors TEXT,
  target_country TEXT,
  story_id INTEGER,
  sentence_number INTEGER,
  publisher TEXT,
  city TEXT,
  district TEXT,
  province TEXT,
  country TEXT,
  latitude REAL,
  longitude REAL,
  year INTEGER NOT NULL,
  yearmonth INTEGER NOT NULL,
  source_file TEXT NOT NULL,
  PRIMARY KEY (event_id, event_date)
);
