


#' Setup ICEWS environment variables
#'
#' Checks for and creates several ICEWS environment variables.
#'
#' @param data_dir Where should the raw TSV data be kept?
#' @param use_db Store events in a SQLite database?
#' @param keep_files keep_files If using a database, retain raw data TSV files?
#' @param r_profile If TRUE, this will write config parameters to a .Renviron file.
#'
#' @export
setup_icews <- function(data_dir, use_db = TRUE, keep_files = FALSE, r_profile = TRUE) {
  if (!dir.exists(data_dir)) {
    stop("Data directory does not exist.")
  }
  if (!use_db %in% c(TRUE, FALSE)) {
    stop("use_db should be TRUE or FALSE")
  }

  set_icews_opts(data_dir, use_db, keep_files)

  # Create folders as neccessary
  if (use_db & !dir.exists(find_db())) {
    dir.create(find_db())
  }
  if ((!use_db | keep_files) & !dir.exists(find_raw())) {
    dir.create(find_raw())
  }

  if(isTRUE(r_profile)) {
    if (!requireNamespace("usethis", quietly = TRUE)) {
      stop("Package \"usethis\" needed for this function to work. Please install it (recommended) or set 'r_environ = FALSE'.",
           call. = FALSE)
    }
    cat("Add these lines to the .Rprofile file:\n\n")
    cat("# ICEWS data location and options\n")
    cat(sprintf("options(icews.data_dir   = \"%s\")\n", data_dir))
    cat(sprintf("options(icews.use_db     = %s)\n", use_db))
    cat(sprintf("options(icews.keep_files = %s)\n", keep_files))
    cat("\n")
    usethis::edit_r_profile()
  }
  cat("Path options are set\n")
  invisible(NULL)
}

#' Set ICEWS options
#'
#' @param data_dir Where should the raw TSV data be kept?
#' @param use_db Store events in a SQLite database?
#' @param keep_files keep_files If using a database, retain raw data TSV files?
#'
#' @export
set_icews_opts <- function(data_dir, use_db, keep_files) {
  options(icews.data_dir   = data_dir)
  options(icews.use_db     = use_db)
  options(icews.keep_files = keep_files)
  invisible(NULL)
}

#' Unset ICEWS options
#'
#' @return Silently returns a list of prior option values to make it possible
#'   reset the values if needed. See [get_icews_opts()] and
#'   [set_icews_opts()].
#'
#' @md
#' @export
unset_icews_opts <- function() {
  opts <- get_icews_opts()
  options(icews.data_dir   = NULL)
  options(icews.use_db     = NULL)
  options(icews.keep_files = NULL)
  invisible(opts)
}


#' Get ICEWS options
#'
#' List the current ICEWS-related option values
#'
#' @seealso [set_icews_opts()], [unset_icews_opts()], [setup_icews()]
#'
#' @export
#' @md
get_icews_opts <- function() {
  out <- list(
    data_dir = getOption("icews.data_dir"),
    use_db   = getOption("icews.use_db"),
    keep_files = getOption("icews.keep_files")
  )
  class(out) <- "icews_opts"
  out
}

#' Format setup use case
#'
#' @param opts List of options generated by [get_icews_opts()]
opts_string <- function(opts) {
  if (is.null(opts$use_db)) {
    return("Options not set")
  }
  if (isFALSE(opts$use_db)) {
    return("File-based option\n")
  }
  str <- "Database option"
  if (isTRUE(opts$keep_files)) {
    str <- paste0(str, ", keep files")
  }
  str
}

#' Format ICEWS opts
#'
#' @param x Object generated by [get_icews_opts()].
#' @param ... Not used
#'
#' @export
#' @md
format.icews_opts <- function(x, ...) {
  opts <- get_icews_opts()
  str  <- list()
  for (i in seq_along(opts)) {
    str[i] <- paste0(names(opts)[i], ": ", opts[i])
  }
  #str <- paste0(str, collapse = "\n")
  smry <- opts_string(opts)
  unlist(c(smry, str))
}

#' Print current ICEWS options
#'
#' @param x Object generated by [get_icews_opts()].
#' @param ... Not used
#'
#' @export
#' @md
print.icews_opts <- function(x, ...) {
   str <- format(x)
   cat(paste0(str, collapse = "\n"))
}


#' Generic path finder
#'
#' @param x The kind of path to find; "db", "raw", or "docs".
find_path <- function(x) {
  data_dir <- getOption("icews.data_dir")
  if (!is.null(data_dir)) {
    suffix <- switch(x,
                     db   = "db/icews.sqlite3",
                     raw  = "raw",
                     docs = "docs")
    path <- file.path(data_dir, suffix)
    return(path)
  }
  lines <- c(
    "Path argument is missing.",
    "Consider setting the paths up globally with `setup_icews()`.",
    "Ideally in your .Rprofile file; try running `dr_icews()` for help."
  )
  stop(paste(lines, collapse = "\n"))
}

#' Find database path
find_db <- function() {
  find_path("db")
}

#' Find raw file directory
find_raw <- function() {
  find_path("raw")
}

#' Find docs directory
find_docs <- function() {
  find_path("docs")
}
